topology:
  mode: "walker"  # 使用Walker模式
  orbital_planes: 6  # 轨道面数量 (P)
  satellites_per_plane: 11  # 每个轨道面的卫星数 (T/P)
  phase_factor: 2  # 相位因子F (0 ≤ F < P)
  altitude: 781  # 轨道高度(km)
  inclination: 86.4  # 轨道倾角(度)
  max_range: 5000  # 最大通信范围(km)
  link:
    frequency: 23e9  # Ka频段 23GHz
    transmit_power: 10.0  # 发射功率(W)
    noise_temperature: 290  # 噪声温度(K)
    bandwidth: 1e9  # 带宽(Hz)
    intra_plane_range: [4021, 4042]  # 同轨道面链路距离范围(km)
    inter_plane_range: [2700, 4400]  # 相邻轨道面链路距离范围(km)
    max_latitude: 65.0  # 相邻轨道面链路的最大纬度(度)

simulation:
  # Walker特定的仿真参数
  network:
    total_satellites: 66  # 总卫星数 T = P * (T/P)
    orbital_planes: 6  # P
    satellites_per_plane: 11  # T/P

  # Walker特定的链路参数
  link:
    bandwidth: 1e9  # 带宽(Hz)
    transmit_power: 10.0
    noise_temperature: 290
    path_loss_model:
      frequency: 23e9  # Ka频段 23GHz
    capacity: 1e9  # 链路容量(bps) 